server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kidshop
    username: postgres
    password: root00
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        ddl-auto: update
  jackson:
    deserialization:
      USE_BIG_DECIMAL_FOR_FLOATS: true

logging:
  level:
    org.springframework: ERROR
    ru.dressyourkid: DEBUG
